# see https://starship.rs/config/ for more info
add_newline = false

[aws]
disabled = true

[battery]
disabled = true

[character]
symbol = "➜"

[directory]
truncation_length = 8
truncate_to_repo = false

[dotnet]
disabled = true

[kubernetes]
disabled = true

[conda]
disabled = true
